skip_operations:
  - CreateIncidentAttachment
  - DeleteIncidentAttachment
  - UpdateIncidentAttachment
  - CreateUserNotificationRule
  - DeleteUserNotificationRule
  - GetUserNotificationRule
  - ListUserNotificationRules
  - UpdateUserNotificationRule
  - MakeGCPSTSDelegate
  - SubmitLog
  - UploadCustomCostsFile
  - CreateTeamNotificationRule
  - DeleteTeamNotificationRule
  - GetTeamNotificationRule
  - GetTeamNotificationRules
  - UpdateTeamNotificationRule

bundle_aliases:
  actions_datastores:
    - datastores
    - datastore
  action_connection:
    - connection
  application_security:
    - appsec
  cloud_cost_management:
    - ccm
  microsoft_teams_integration:
    - msteams-integration
  networkd_device_monitoring:
    - ndm
  sensitive_data_scanner:
    - sds
  service_level_objectives:
    - slo
  service_scorecards:
    - scorecards
    - scorecard
  workflow_automation:
    - workflow
    - wf

acronyms:
  - AD
  - AI
  - APIs
  - API
  - AWS
  - CI
  - GCP
  - CPU
  - CSM
  - DORA
  - IAM
  - ID
  - IP
  - JSON
  - RUM
  - SBOM
  - SCA
  - SLO
  - STS
  - WAF
  - CUR
  - UC
