skip_operations:
  - CreateIncidentAttachment
  - DeleteIncidentAttachment
  - UpdateIncidentAttachment
  - CreateUserNotificationRule
  - DeleteUserNotificationRule
  - GetUserNotificationRule
  - ListUserNotificationRules
  - UpdateUserNotificationRule
  - MakeGCPSTSDelegate
  - SubmitLog
  - UploadCustomCostsFile

optional_parameters_operations:
  SearchCIAppTestEvents: SearchCIAppTestEventsOptionalParameters
  SearchCIAppPipelineEvents: SearchCIAppPipelineEventsOptionalParameters
  SearchAuditLogs: SearchAuditLogsOptionalParameters
  SearchEvents: SearchEventsOptionalParameters
  CreateOpenAPI: CreateOpenAPIOptionalParameters
  UpdateOpenAPI: UpdateOpenAPIOptionalParameters
  ListLogs: ListLogsOptionalParameters
  UploadIdPMetadata: UploadIdPMetadataOptionalParameters
  SearchFlakyTests: SearchFlakyTestsOptionalParameters
  SearchSecurityMonitoringHistsignals: SearchSecurityMonitoringHistsignalsOptionalParameters
  SearchSecurityMonitoringSignals: SearchSecurityMonitoringSignalsOptionalParameters
