skip_operations:
  - CreateIncidentAttachment
  - DeleteIncidentAttachment
  - UpdateIncidentAttachment
  - CreateUserNotificationRule
  - DeleteUserNotificationRule
  - GetUserNotificationRule
  - ListUserNotificationRules
  - UpdateUserNotificationRule
  - MakeGCPSTSDelegate
  - SubmitLog
  - UploadCustomCostsFile

optional_parameters_operations:
  SearchCIAppTestEvents: SearchCIAppTestEventsOptionalParameters
  SearchCIAppPipelineEvents: SearchCIAppPipelineEventsOptionalParameters
  SearchAuditLogs: SearchAuditLogsOptionalParameters
  SearchEvents: SearchEventsOptionalParameters
  CreateOpenAPI: CreateOpenAPIOptionalParameters
  UpdateOpenAPI: UpdateOpenAPIOptionalParameters
  ListLogs: ListLogsOptionalParameters
  UploadIdPMetadata: UploadIdPMetadataOptionalParameters
  SearchFlakyTests: SearchFlakyTestsOptionalParameters
  SearchSecurityMonitoringHistsignals: SearchSecurityMonitoringHistsignalsOptionalParameters
  SearchSecurityMonitoringSignals: SearchSecurityMonitoringSignalsOptionalParameters

tag_aliases:
  actions_datastores:
    - datastores
  action_connection:
    - connection
  application_security:
    - appsec
  cloud_cost_management:
    - ccm
  microsoft_teams_integration:
    - microsoft_teams
  networkd_device_monitoring:
    - ndm
  sensitive_data_scanner:
    - sds
  service_level_objectives:
    - slo
  service_scorecards:
    - scorecards
  workflow_automation:
    - workflow
    - wf

acronyms:
  - AD
  - AI
  - API
  - AWS
  - CI
  - GCP
  - CPU
  - CSM
  - DORA
  - IAM
  - ID
  - IP
  - JSON
  - RUM
  - SBOM
  - SCA
  - SLO
  - STS
  - WAF
  - CUR
  - UC
